databases:
  database: 
    host: localhost
    username: username
    password: password
    database: database
    primary: true
environment: DEVELOPMENT
discord:
  token: ""
motd: 
  - "&d&lThe Nexus Reborn &7&l-> &e&lALPHA &7[1.8-1.21.5]"
  - "&7Discord: &3thenexusreborn.com/discord"