main: com.thenexusreborn.nexuscore.NexusCore
version: ${project.version}
name: NexusCore
description: The main core of The Nexus Reborn
author: Firestar311
commands:
  rank:
    description: Set player ranks
  setstat:
    description: Set stats
  consolodateStats:
    description: Consolodates stats