main: com.thenexusreborn.nexuscore.NexusCore
version: ${project.version}
name: NexusCore
description: The main core of The Nexus Reborn
author: Firestar311
depend: [StarCore, StarUI, StarChat, PlaceholderAPI]
softdepend: [Vulcan]
commands:
  rank:
    description: Set player ranks
  setstat:
    description: Set stats
  tag:
  message:
    aliases: [msg, whisper, tell]
  reply:
    aliases: [r]
  say:
  me: 
  discord:
  shop:
    aliases: [store]
  ban:
  tempban:
    aliases: [tb]
  mute:
  tempmute:
    aliases: [tm]
  kick:
  warn:
  blacklist:
  unban:
  unmute:
  unblacklist:
  pardon:
  history:
  staffhistory:
  alts:
  vanish:
    aliases: [v]
  incognito:
    aliases: [i]
  fly:
  nexusversion: 
  tps:
    aliases: [performance, memory, mem, perf]
  playtime:
  list:
  balance:
    aliases: [bal]