main: com.thenexusreborn.nexuscore.NexusCore
version: ${project.version}
name: NexusCore
description: The main core of The Nexus Reborn
author: Firestar311
commands:
  rank:
    description: Set player ranks
  setstat:
    description: Set stats
  consolodateStats:
    description: Consolodates stats
  tag:
  message:
    aliases: [msg, whisper, tell]
  reply:
    aliases: [r]
  say:
  me: 
  discord:
  shop:
    aliases: [store]
  ban:
  tempban:
    aliases: [tb]
  mute:
  tempmute:
    aliases: [tm]
  kick:
  warn:
  blacklist:
  unban:
  unmute:
  unblacklist:
  pardon:
  history:
  staffhistory: