main: com.thenexusreborn.nexuscore.NexusCore
version: ${version}
name: NexusCore
description: The main core of The Nexus Reborn
author: Firestar311
depend: [StarCore, StarChat, PlaceholderAPI]
softdepend: [Vulcan]
commands:
  rank:
    description: Set player ranks
  tag:
  message:
    aliases: [msg, whisper, tell, w]
  reply:
    aliases: [r]
  say:
  discord:
  shop:
    aliases: [store]
  ban:
  tempban:
    aliases: [tb]
  mute:
  tempmute:
    aliases: [tm]
  kick:
  warn:
  blacklist:
  unban:
  unmute:
  unblacklist:
  pardon:
  history:
  staffhistory:
  alts:
  vanish:
    aliases: [v]
  incognito:
    aliases: [i]
  fly:
  nexusversion: 
  tps:
    aliases: [performance, memory, mem, perf]
  playtime:
  list:
  balance:
    aliases: [bal]
  servers:
  verify:
  nexusbot: 
  tagadmin:
  nickname:
    aliases: [nick]
  unnickname:
    aliases: [unnick]
  realname:
  profile:
  nickadmin: 
    aliases: [na]
  debug:
    aliases: [dbug]
  toggleop:
  ping: 